version: '2.2'

services:
  influxdb:
    volumes:
      - ./migration/influxdb:/tmp/migration

  web:
    volumes:
      - ../stations:/tmp/migration

  mariadb:
    volumes:
      - ./migration/database.sql:/tmp/database.sql
