version: '2.2'

services:
  static:
    build:
      context: ./util/docker/static
    volumes:
      - ./web/static:/data
      - static_node_modules:/data/node_modules

volumes:
  static_node_modules: {}
