---
- name: Generate Cron Template
  template: src=azuracast_cron.j2 dest="{{ tmp_base }}/azuracast_cron" force=true

- name: Install Cron file
  shell: "crontab -u azuracast {{ tmp_base }}/azuracast_cron"
  notify: restart cron

- name: Clean up temp Cron file
  file: path="{{ tmp_base }}/azuracast_cron" state=absent